# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check if a point is contained within a polygon
#'
#' @param point A \code{rowvec} with x,y coordinate structure.
#' @param vertices A \code{matrix} containing the boundary points of the polygon.
#' @return A \code{bool} indicating whether the point is in the polygon (TRUE) or not (FALSE)
pointInPoly <- function(point, vertices) {
    .Call('_edmaps_pointInPoly', PACKAGE = 'edmaps', point, vertices)
}

#' Check if multiple points are contained within a polygon
#'
#' @param points A \code{matrix} with x,y coordinate structure.
#' @param vertices A \code{field} of type {matrix} that contains the polygon coordinates to test against.
#' @return A logical \code{vector} indicating whether each point is within the polygon.
pointsInPoly <- function(points, vertices) {
    .Call('_edmaps_pointsInPoly', PACKAGE = 'edmaps', points, vertices)
}

